# For workspace name
# The checkpoint file location to be saved: {workspace}/checkpoints/
# The log file location to be saved: {workspace}/tensorboard_logs/
workspace: /datadrive/rakesh/ingram_rakesh_data/results/custom_trial

dataset: custom
dataset_root_path: /datadrive/rakesh/ingram_rakesh_data/data_in_funsd_format/dataset
task: ee_el
img_h: 768
img_w: 768

seed: 1
cudnn_deterministic: False
cudnn_benchmark: False

model:
  #n_classes: 40
  backbone: alibaba-damo/geolayoutlm-large-uncased
  config_json: ./configs/GeoLayoutLM/GeoLayoutLM_large_model_config.json
  model_ckpt: /home/gpu1admin/rakesh/geo-layout-lm-tf-Final_geo_training_inference_scripts/geolayoutlm_large_pretrain.pt #geolayoutlm_large_pretrain #epoch=12-f1_labeling=0.9070.pt #epoch=23-f1_labeling=0.9318.pt
  head: vie
  use_inner_id: true
  max_prob_as_father: true
  max_prob_as_father_upperbound: false

train:
  batch_size: 1
  num_samples_per_epoch: 1680
  max_seq_length: 512
  max_block_num: 150
  max_epochs: 50
  use_fp16: False
  accelerator: gpu
  strategy:
    type: ""

  clip_gradient_algorithm: norm
  clip_gradient_value: 1.0
  num_workers: 2

  optimizer:
    method: adamw
    params:
      lr: 2e-5
      weight_decay: 0.01
      eps: !!float 1e-8
    lr_schedule:
      method: linear
      params:
        warmup_steps: 200

  val_interval: 1  # in epochs

val:
  batch_size: 1
  num_workers: 2
  limit_val_batches: 1.0
  dump_dir: /home/ntlpt19/Downloads/MERGED_DATA/GEO_Latest/geolayoutlm_code_base_2/CI_EVAL/val_inference_files/dataset
  pretrained_best_type: linking # labeling, linking

pretrained_model_file: ~ #geolayoutlm_large_pretrain.pt

doc-type:
  CS: 
    
  COO:

  PL:

  IC:

  BOL: