; config.ini
[OCR]
gv_key = /home/ntlpt19/TF_testing_EXT/code/miscellaneous_code/src/main/gv_key.json
ENGINE = Vision
FILE_PAGE_LIMIT = 15
RAM_LIMIT = 400
FILE_SIZE_LIMIT = 50000000

[PATHS]
folder_path = /home/ntlpt19/Downloads/Final_Delivery_Training_itter_5/CI_verified_annotations/CI_train_604

[PARAMS]
thresh_value = 300
label_length = 30
div_value = 2
color_val = 225
thick_val = 4
percent_val = 0.40
nill_val = 0
zoom_val = 72
thick_val2 = 2
random_seed_val = 10
train_div_ratio = 0.1
intersect_per = 1.0
intersect_per2 = 0.0
norm_val = 1000
out_label_ids = 100
encoded_size = 512

[SERVICE]
API_PORT = 8181
API_THREAD_POOL = 1
API_QUEUE_SIZE = 5
API_PROXY_BASE = 127.0.0.1
API_SOCKET_HOST = 0.0.0.0
API_LOGS = logs.txt
API_R_LOGS = response_log.txt

[LOG]
LOG_PATH = 
LOG_FILESIZE = 10
LOG_FILEROLLBACKUPS = 10
LOG_FILTER_LEVELMIN = DEBUG
APPLOG_FILE = app_log.txt
APPLOG_DIRECTORY = APPLOG

[All_MODEL]
LIST = ['INVOICE_MODEL']

[INVOICE_MODEL]
MODEL_PATH = Model_20_epochs_latest
MODEL_NAME = pytorch_model.bin
MODEL_CONFIG = config.json
MODEL_DES = Invoice
LIC_ID = ['ox','tf']
FIELD_PATH=model_info.txt

[Default]
ALPHA = 1.6

[bill_to]
ALPHA = 1.6

[ship_to]
ALPHA = 1.6

[remit_to]
ALPHA = 1.6

[vendor_name]
ALPHA = 1.6

[new_line]
print_new_line = True

[dimension]
Pixel_limit = 20000000

[lookup]
lookup_fields = ["bill_to","remit_to", "ship_to"]
lookup_details = {"bill_to": ["country","organization"], "ship_to": ["country","organization"], "remit_to": ["country","organization"]}