keys_to_find = [
    "beneficiary_account_number",
    "beneficiary_address",
    "beneficiary_bank_name",
    "beneficiary_drawer_exporter_seller_supplier_name",
    "beneficiary_drawer_exporter_seller_supplier_tin",
    "bill_of_lading_date",
    "bill_of_lading_no",
    "consignee_address",
    "cosignee_name",
    "country_of_final_destination",
    "country_of_origin_of_goods",
    "date_of_invoice",
    "declaration_by_issuer",
    "delivery_terms",
    "goods_description",
    "incoterm",
    "indicator_date",
    "indicator_type",
    "invoice_amount",
    "invoice_amount_in_words",
    "invoice_currency",
    "invoice_due_date",
    "invoice_no",
    "lc_date",
    "lc_ref_no",
    "net_weight",
    "original_or_copy",
    "page_no",
    "remitter_address",
    "remitter_drawee_applicant_importer_buyer_name",
    "tenor_indicator",
    "total_quantity_of_goods",
    "usance_tenor",
    "vessel_flight_no",
    "vessel_name"
]


field_indices = {
    'transaction_date': 0,
    'remitter_drawee_applicant_importer_buyer_name': 1,
    'remitter_address': 2,
    'remitter_country': 3,
    'cosignee_name': 4,
    'consignee_address': 5,
    'consignee_country': 6,
    'notify_party_name': 7,
    'notify_party_address': 8,
    'notify_party_country': 9,
    'beneficiary_drawer_exporter_seller_supplier_name': 10,
    'beneficiary_drawer_exporter_seller_supplier_tin': 11,
    'beneficiary_address': 12,
    'beneficiary_country': 13,
    'consignor_name': 14,
    'consignor_address': 15,
    'consignor_country': 16,
    'shipper_name': 17,
    'shipper_address': 18,
    'shipper_country': 19,
    'transaction_currency': 20,
    'transaction_amonunt_value': 21,
    'invoice_no': 22,
    'date_of_invoice': 23,
    'invoice_currency': 24,
    'invoice_amount': 25,
    'invoice_discount_ccy': 26,
    'invoice_discount_amount': 27,
    'invoice_tax_ccy': 28,
    'invoice_tax_amount': 29,
    'invoice_amount_in_words': 30,
    'goods_description': 31,
    'total_quantity_of_goods': 32,
    'rate_per_unit': 33,
    'gross_weight': 34,
    'net_weight': 35,
    'dimension': 36,
    'hs_code_no': 37,
    'beneficiary_bank_name': 38,
    'beneficiary_bank_country': 39,
    'beneficiary_account_number': 40,
    'beneficiary_iban_number': 41,
    'beneficiary_bank_identifier': 42,
    'delivery_terms': 43,
    'tenor_type': 44,
    'usance_tenor': 45,
    'tenor_indicator': 46,
    'indicator_type': 47,
    'indicator_date': 48,
    'invoice_due_date': 49,
    'incoterm': 50,
    'country_of_origin_of_goods': 51,
    'port_of_loading': 52,
    'port_of_discharge': 53,
    'country_of_final_destination': 54,
    'pre-carriage-by': 55,
    'vessel_flight_no': 56,
    'bill_of_lading_no': 57,
    'bill_of_lading_date': 58,
    'awb_number': 59,
    'awb_date': 60,
    'page_no': 61,
    'declaration_by_issuer': 62,
    'signature_of_the_issuer': 63,
    'original_or_copy': 64,
    'lc_ref_no': 65,
    'lc_date': 66,
    'stamp': 67,
    'signature': 68,
    'vessel_name': 69,
    'place_of_receipt': 70,
    'additional_charges': 71,
    'freight_charges': 72,
    'insurance_charges': 73,
    'draft_number': 74
}
# Extract the indices
result_indices = {key: field_indices.get(key, None) for key in keys_to_find}
val_list = []
for key, value in result_indices.items():
    val_list.append(value)
# Print the result
print(result_indices)
print(val_list)
keys_not_to_consider = []
for i in range(0, 75):
    if i not in val_list:
        keys_not_to_consider.append(i)
print(keys_not_to_consider)